### ISSUE TITLE
Node-Red broken after HA Update (0.105.2 + OS update)

### ISSUE THREAD

**Issue by cjramseyer** [hassio-addons/repository#174]
# Problem/Motivation

>I have been running Node-Red for all of my automations.  It has been working great and so far been extremely stable.  I upgrade Home-Assistant (rPi 3B+, HA 0.105.2, HassOS 3.9)

## Expected behavior

>I expected Node-Red to start/restart after the upgrade

## Actual behavior

>Node-Red attempted to start, complained about many plugins, including telegram, and nginx (I am not using either but had the nodes installed to the palette)

## Steps to reproduce

>Update HA to latest version and restart addins

## Proposed changes

>Please share a fiox for this without having to reinstall (working on that currently) and offer a "repair/safe mode" option so node-red can start to allow possible fixes for errors

**Comment by sinclairpaul** [comment]
Can you please share the addon and supervisor logs, it is difficult to assist without knowing the issue.

**Comment by cjramseyer** [comment]
at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 298)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 299)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 300)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /red/images/typedInput/json.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/entities HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /red/images/typedInput/expr.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/services HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/entities HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/services HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/entities HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:08 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/services HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
9 Feb 21:17:08 - [info] [mqtt-broker:HASSIO Mosquitto Broker] Connection failed to broker: mqtt://localhost:1883
[09/Feb/2020:21:17:12 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /credentials/server/45c3e356.d307ec HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 301)
[09/Feb/2020:21:17:17 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/entities HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:21:17:17 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) GET /homeassistant/45c3e356.d307ec/services HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 302)
9 Feb 21:17:23 - [info] [mqtt-broker:HASSIO Mosquitto Broker] Connection failed to broker: mqtt://localhost:1883
9 Feb 21:17:25 - [info] Stopping flows
9 Feb 21:17:25 - [info] Stopped flows
9 Feb 21:17:25 - [info] Starting flows
9 Feb 21:17:26 - [info] Started flows
[09/Feb/2020:21:17:26 -0500] 200 10.0.0.101, 172.30.32.1(172.30.32.2) POST /flows HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
9 Feb 21:17:26 - [info] [mqtt-broker:HASSIO Mosquitto Broker] Connection failed to broker: mqtt://localhost:1883
9 Feb 21:17:27 - [error] [api-call-service:Toggle Node-Red Watchdog] Call-Service attempted without connection to server.
9 Feb 21:17:27 - [error] [api-call-service:House Mode: Evening] Call-Service attempted without connection to server.
9 Feb 21:17:27 - [error] [api-call-service:Turn On - Exterior Lights] Call-Service attempted without connection to server.
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 303)
9 Feb 21:17:27 - [error] [api-call-service:Turn tori nightlight off] Call-Service attempted without connection to server.
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 304)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 305)
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 306)
9 Feb 21:17:27 - [error] [api-call-service:Turn general nightlight(s) off] Call-Service attempted without connection to server.
9 Feb 21:17:30 - [info] [server:Home Assistant] WebSocket Connecting http://hassio/homeassistant
9 Feb 21:17:30 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 307)
9 Feb 21:17:41 - [info] [mqtt-broker:HASSIO Mosquitto Broker] Connection failed to broker: mqtt://localhost:1883
(node:545) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at CurrentStateNode.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/current-state/current-state.js:58:54)
    at CurrentStateNode.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/base-node.js:544:18)
    at CurrentStateNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:439:21)
(node:545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 308)

**Comment by cjramseyer** [comment]
I reinstalled Node-Red and reimported my flows, so I have managed to restore my flows architecture.  But I am having trouble restoring connectivity to hassio (hassos).  The above error log is from my reinstallation.

**Comment by sinclairpaul** [comment]
Not sure why the HA flows cause an issue, would suggest checking the setup for them and validating whats in the Supervisor log.

Your MQTT credentials/setup also seem to be wrong.

I will add that the challenge with Node Red is that anyone can publish to NPM, and not necessarily maintain the package, which means as dependencies are updated, they can break.

You should be able to issue npm uninstall commands from the addon config, I will look at the possibility of a "reset" function.

**Comment by cjramseyer** [comment]
I am reinstalling Node-Red again, after importing my flows from a backup, I could not get them to connect to HA.  But I can't figure out why.  I have 100s of nodes, since I use Node-Red exclusively as my automation engine.  Appreciate any suggestions.

**Comment by sinclairpaul** [comment]
What does the supervisor log say, and did you restore from a snapshot, or re-importing?

Can you validate what is set on the HA server config:

![image](https://user-images.githubusercontent.com/24625998/74191436-8fe4f500-4c21-11ea-8be7-1440560bd598.png)
