### ISSUE TITLE
Unable to start node-red-contrib-rfxcom

### ISSUE THREAD

**Issue by paddenstoeltje** [hassio-addons/repository#189]
# Problem/Motivation
I'm unable to start node red in Hass.io with the node-red-contrib-rfxcom library. 

## Expected behavior

Node red should load the RFXcom library correctly.

## Actual behavior

I get the following error:
2020-07-06T13:55:44.309Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-rfxcom@2.11.0
2020-07-06T13:55:55.701Z [out] 
2020-07-06T13:55:55.701Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-07-06T13:55:55.701Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-07-06T13:55:55.701Z [out] 
2020-07-06T13:55:56.711Z [err] prebuild-install
2020-07-06T13:55:56.711Z [err]  WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
2020-07-06T13:55:58.217Z [err] gyp
2020-07-06T13:55:58.218Z [err]  
2020-07-06T13:55:58.218Z [err] ERR! build error 
2020-07-06T13:55:58.220Z [err] gyp
2020-07-06T13:55:58.220Z [err]  ERR! stack
2020-07-06T13:55:58.221Z [err]  Error: not found: make
2020-07-06T13:55:58.221Z [err] gyp ERR!
2020-07-06T13:55:58.221Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-06T13:55:58.221Z [err] gyp 
2020-07-06T13:55:58.221Z [err] ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-06T13:55:58.221Z [err] gyp ERR! stack
2020-07-06T13:55:58.221Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-06T13:55:58.221Z [err] gyp ERR! 
2020-07-06T13:55:58.222Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-06T13:55:58.222Z [err] gyp ERR!
2020-07-06T13:55:58.222Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-06T13:55:58.222Z [err] gyp ERR!
2020-07-06T13:55:58.222Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-06T13:55:58.222Z [err] gyp 
2020-07-06T13:55:58.222Z [err] ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-07-06T13:55:58.223Z [err] gyp
2020-07-06T13:55:58.223Z [err]  ERR! System Linux 4.19.127-v7l
2020-07-06T13:55:58.223Z [err] gyp
2020-07-06T13:55:58.223Z [err]  ERR! command
2020-07-06T13:55:58.223Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-07-06T13:55:58.223Z [err] gyp 
2020-07-06T13:55:58.223Z [err] ERR! cwd /config/node-red/node_modules/@serialport/bindings
2020-07-06T13:55:58.223Z [err] gyp ERR!
2020-07-06T13:55:58.223Z [err]  node -v v12.15.0
2020-07-06T13:55:58.224Z [err] gyp ERR! 
2020-07-06T13:55:58.224Z [err] node-gyp -v v5.0.5
2020-07-06T13:55:58.224Z [err] gyp ERR! not ok
2020-07-06T13:55:58.224Z [err]  
2020-07-06T13:55:58.730Z [err] npm
2020-07-06T13:55:58.730Z [err]  
2020-07-06T13:55:58.730Z [err] ERR!
2020-07-06T13:55:58.731Z [err]  
2020-07-06T13:55:58.731Z [err] code
2020-07-06T13:55:58.731Z [err]  ELIFECYCLE
2020-07-06T13:55:58.731Z [err] npm
2020-07-06T13:55:58.732Z [err]  
2020-07-06T13:55:58.732Z [err] ERR!
2020-07-06T13:55:58.732Z [err]  
2020-07-06T13:55:58.732Z [err] errno
2020-07-06T13:55:58.732Z [err]  1
2020-07-06T13:55:58.735Z [err] npm
2020-07-06T13:55:58.735Z [err]  
2020-07-06T13:55:58.736Z [err] ERR!
2020-07-06T13:55:58.736Z [err]  @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-07-06T13:55:58.736Z [err] npm
2020-07-06T13:55:58.736Z [err]  
2020-07-06T13:55:58.737Z [err] ERR!
2020-07-06T13:55:58.737Z [err]  Exit status 1
2020-07-06T13:55:58.737Z [err] npm
2020-07-06T13:55:58.737Z [err]  
2020-07-06T13:55:58.737Z [err] ERR!
2020-07-06T13:55:58.738Z [err]  
2020-07-06T13:55:58.738Z [err] npm
2020-07-06T13:55:58.738Z [err]  
2020-07-06T13:55:58.738Z [err] ERR!
2020-07-06T13:55:58.738Z [err]  Failed at the @serialport/bindings@8.0.8 install script.
2020-07-06T13:55:58.739Z [err] npm
2020-07-06T13:55:58.739Z [err]  
2020-07-06T13:55:58.739Z [err] ERR!
2020-07-06T13:55:58.739Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-07-06T13:55:58.771Z [err] 
2020-07-06T13:55:58.772Z [err] npm
2020-07-06T13:55:58.772Z [err]  
2020-07-06T13:55:58.772Z [err] ERR!
2020-07-06T13:55:58.772Z [err]  A complete log of this run can be found in:
2020-07-06T13:55:58.772Z [err] npm
2020-07-06T13:55:58.773Z [err]  
2020-07-06T13:55:58.773Z [err] ERR!
2020-07-06T13:55:58.773Z [err]      /root/.npm/_logs/2020-07-06T13_55_58_760Z-debug.log
2020-07-06T13:55:58.789Z rc=1

## Steps to reproduce

Load the node-red-contrib-rfxcom library with Hass.io Node-red 6.3.0
RPI4, HassOS 4.11

## Proposed changes
No idea. I expect something is missing or not up to date in the container?

**Comment by paddenstoeltje** [comment]
Posted in the wrong place.
