### ISSUE TITLE
There was an error when installed the plugin

### ISSUE THREAD

**Issue by cuihaijun** [hassio-addons/repository#6]
Options
{
  "debug": true,
  "plugins": [
    "homebridge-config-ui"
  ]
}

Logs
.....................
Registering new address record for 169.254.65.124 on veth1c062f4.IPv4.
Registering new address record for fe80::a61a:18a7:f739:a3f6 on docker0.*.
Registering new address record for 169.254.85.176 on docker0.IPv4.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for 192.168.1.188 on eth0.IPv4.
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by frenck** [comment]
@cuihaijun Thank you for reporting this issue.

This is kinda a known issue with the NPM `mdns` package, I will take a look at it and see if I can support it in a future version.

**Comment by frenck** [comment]
Small update:

I've found and fixed this issue in local development, so you can expect a release soon.

**Comment by frenck** [comment]
Reopening issue, still needs to be released....

**Comment by frenck** [comment]
This issue has been fixed in v1.0.2 of the plugin. 

For more information check [this community forum topic](https://community.home-assistant.io/t/repository-community-hass-io-add-ons/24705/21?u=frenck).
